version: "3.4"
services:
  
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_USER=dangerous
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=rotmgprod
    volumes:
      - ./db:/var/lib/mysql
      - ./startup:/docker-entrypoint-initdb.d
    ports:
      - "3305:3306"
      

#  admitier:
#    image: adminer
#    restart: always
#    ports:
#    - 8080:8080