FROM mysql:5

WORKDIR /app

#VOLUME C:/Users/davi.henrique/Desktop/deploy/ROTMG/db/docker/startup:/docker-entrypoint-initdb.d
#
#VOLUME C:/Users/davi.henrique/Desktop/deploy/ROTMG/db/docker/:/var/lib/mysql

EXPOSE 3306